<?php

if ($_SERVER['HTTP_HOST'] == 'islandora-dev.local') {
  define('CONFERENCE_CMODEL', 'islandora:dtuConferenceCmodel');
  define('CONFERENCE_COLLECTION_PID', 'islandora:296');
  define('CONTRIBUTION_CMODEL', 'islandora:dtuContributionCmodel');
  define('DOCUMENT_CMODEL', 'islandora:dtuDocumentCmodel');
  define('REPO_URL', 'http://dtu-phase2.dgi:8080/fedora/get/');
}
else {
  define('CONFERENCE_CMODEL', 'dtu:conferenceCModel');
  define('CONFERENCE_COLLECTION_PID', 'dtu:conferences');
  define('CONTRIBUTION_CMODEL', 'dtu:contributionCModel');
  define('DOCUMENT_CMODEL', 'dtu:documentCModel');
  define('REPO_URL', 'http://dtu-phase2.dgi:8080/fedora/get/');
}

/**
 * Implementation of hook_init()
 */
function dtu_init() {
  // Include javascript for datatables (UI improvements for conference and contribution lists)
  drupal_add_js(drupal_get_path('module', 'dtu') . '/datatable/media/js/jquery.dataTables.min.js');
  drupal_add_js(drupal_get_path('module', 'dtu') . '/js/dtu.js');
  drupal_add_css(drupal_get_path('module', 'dtu') . '/datatable/media/css/jquery.dataTables.css');
  
  if (isset($_GET['conference'])) {
    $_SESSION['conference'] = $_GET['conference'];
  }
  
  if (isset($_GET['type'])) {
    $_SESSION['document_type'] = $_GET['type'];
  }
  
  if (isset($_GET['contribution'])) {
    $_SESSION['contribution'] = $_GET['contribution'];
  }
}

/**
 * Implementation of hook_menu()
 */
function dtu_menu() {
  $items = array();
  
  $items['admin/conference/list'] = array(
    'title' => t('Conferences'),
    'page callback' => 'dtu_conference_list',
    'access arguments' => array('administer conferences'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'pages/conferences.inc',
  );
  $items['admin/conference/%/delete'] = array(
    'title' => t('Delete Conference'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dtu_conference_delete_form', 2),
    'access arguments' => array('delete conference'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'pages/conferences.inc',
  );
  $items['admin/conference/%/document/%'] = array(
    'title' => t('Edit Conference Document'),
    'page callback' => 'dtu_conference_document_form_redirect',
    'page arguments' => array(2, 4),
    'access arguments' => array('administer conference'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'pages/conferences.inc',
  );
  $items['admin/conference/%/contributions'] = array(
    'title' => t('Contributions'),
    'page callback' => 'dtu_contribution_list',
    'page arguments' => array(2),
    'access arguments' => array('administer contributions'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'pages/contributions.inc',
  );
  $items['admin/conference/%/contribution/%/document/%'] = array(
    'title' => t('Edit Contribution Document'),
    'page callback' => 'dtu_contribution_document_form_redirect',
    'page arguments' => array(2, 4, 6),
    'access arguments' => array('administer contributions'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'pages/contributions.inc',
  );
  $items['admin/contribution/%/delete'] = array(
    'title' => t('Contributions'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dtu_contribution_delete_form', 2),
    'access arguments' => array('delete contribution'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'pages/contributions.inc',
  );
  return $items;
}

/**
 * Implementation of hook_theme()
 */
function dtu_theme($existing, $type, $theme, $path) {
  return array(
    'dtu_conference_admin_list' => array(
      'path' => drupal_get_path('module', 'dtu') . '/templates',
      'arguments' => array(
        'conferences' => NULL,
        'add_conference' => NULL,
      ),
      'template' => 'dtu-conferences-admin-list',
    ),
    'dtu_contribution_admin_list' => array(
      'path' => drupal_get_path('module', 'dtu') . '/templates',
      'arguments' => array(
        'contributions' => NULL,
        'add_contribution' => NULL,
      ),
      'template' => 'dtu-contributions-admin-list',
    ),
    'dtu_conferences_list' => array(
      'path' => drupal_get_path('module', 'dtu') . '/templates',
      'arguments' => array(
        'conferences' => NULL,
      ),
      'template' => 'dtu-conferences-list',
    ),
  );
}

//
// @TODO: implement hook perm
//
function dtu_perm() {
  return array(
    'administer conferences',
    'administer contributions',
    'delete conference',
  );
}

function dtu_block($op, $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $block[0]['info'] = t('Conference List');
      return $block;
    case 'view':
      switch ($delta) {
        case 0:
          module_load_include('inc', 'dtu', 'inc/conference_list');
          $block['subject'] = t('Conference List');
          $block['content'] = dtu_render_conference_block();
          break;
      }
      return $block;
  }
}

/**
 * Implementation of hook_form_alter()
 */
function dtu_form_alter(&$form, &$form_state, $form_id) {
  $form['#validate'][] = 'dtu_conf_validate';
  $form['#submit'][] = 'dtu_conf_submit';

  if (is_array($form['TracksSessions']['SuperEvent']['Track']['Title'])) {
    if (!empty($form['TracksSessions']['SuperEvent']['Track']['Acronym']['#default_value']) && !empty($form['TracksSessions']['SuperEvent']['Track']['Title']['#default_value'])) {
      $track_key = $form['TracksSessions']['SuperEvent']['Track']['Acronym']['#default_value'] . '--delim--' . $form['TracksSessions']['SuperEvent']['Track']['Title']['#default_value'];
      $form['TracksSessions']['SuperEvent']['Track']['Title']['#default_value'] = $track_key;
    }
    
    // Populate proper track options for the contribution
    $form['TracksSessions']['SuperEvent']['Track']['Title']['#options'] = dtu_get_contrib_tracks_sess(arg(2), 'tra', $form);
  }
  
  if (is_array($form['TracksSessions']['SuperEvent']['Session']['Title'])) {
    if (!empty($form['TracksSessions']['SuperEvent']['Session']['Acronym']['#default_value']) && !empty($form['TracksSessions']['SuperEvent']['Session']['Title']['#default_value'])) {
      $sess_key = $form['TracksSessions']['SuperEvent']['Session']['Acronym']['#default_value'] . '--delim--' . $form['TracksSessions']['SuperEvent']['Session']['Title']['#default_value'];
      $form['TracksSessions']['SuperEvent']['Session']['Title']['#default_value'] = $sess_key;
    }
    // Populate proper session options for the contribution
    $form['TracksSessions']['SuperEvent']['Session']['Title']['#options'] = dtu_get_contrib_tracks_sess(arg(2), 'ses', $form);
  }

}

function dtu_islandora_tabs_alter(&$tabs, $params) {
  if (empty($_GET['add_tab']) && !strstr($_SERVER['HTTP_REFERER'], 'add_tab')) {
    unset($tabs['add_tab']);
  }
}

function dtu_islandora_content_model_forms_get_transforms() {
  $path = drupal_get_path('module', 'dtu');

  $transforms = array();

  $transforms[$path . '/transforms/mxe2dc.xsl'] = "mxe2dc.xsl (dtu)";
  $transforms[$path . '/transforms/mxd2dc.xsl'] = "mxd2dc.xsl (dtu)";

  return $transforms;
}

function dtu_conf_validate($form, &$form_state) {

  // Validate person's organisation number matches an existing organisation tab
  if (count($form_state['values']['Persons']['Person'])) {
    $org_count = count($form_state['values']['Persons']['Organisation']);

    $person_num = 0;
    foreach ($form_state['values']['Persons']['Person'] AS $person) {
      $selected_org = $person['PersonParent']['org'];

      if ($selected_org > $org_count) {
        form_set_error('Persons][Person][' . $person_num . '][PersonParent][org', t('The selected organisation reference does not exist'));
      }
      $person_num++;
    }
  }

  if ($form_state['values']['dsid'] == 'MXE') {
    if (!empty($form_state['values']['PrimaryInformation']['DateParent']['DateFrom'])) {
      $from = $form_state['values']['PrimaryInformation']['DateParent']['DateFrom'];
      
      $from_explode = explode("-", $from);
      
      if (is_numeric($from_explode[0]) && strlen($from_explode[0]) == 4) {
        $form_state['values']['PrimaryInformation']['DateParent']['Year'] = $from_explode[0];
        $form_state['values']['PrimaryInformation']['DateParent']['DateFrom'] = $from_explode[2] . '-' . $from_explode[1] . '-' . $from_explode[0];
      }
    }
    
    // reformat to dd-mm-yyyy
    $to = $form_state['values']['PrimaryInformation']['DateParent']['DateTo'];
    $to_explode = explode('-', $to);
    if (!empty($to) && strlen($to_explode[0]) == 4) {
      $form_state['values']['PrimaryInformation']['DateParent']['DateTo'] = $to_explode[2] . '-' . $to_explode[1] . '-' . $to_explode[0];
    }
  }

  if ($form_state['values']['TracksSessions']['SuperEvent']['Session']['Title']) {
    $ses_val = explode('--delim--', $form_state['values']['TracksSessions']['SuperEvent']['Session']['Title']);
    $form_state['values']['TracksSessions']['SuperEvent']['Session'] = '';
    $form_state['values']['TracksSessions']['SuperEvent']['Session']['Title'] = $ses_val[1];
    $form_state['values']['TracksSessions']['SuperEvent']['Session']['Acronym'] = $ses_val[0];
  }
  
  if ($form_state['values']['TracksSessions']['SuperEvent']['Track']['Title']) {
    $track_val = explode('--delim--', $form_state['values']['TracksSessions']['SuperEvent']['Track']['Title']);
    $form_state['values']['TracksSessions']['SuperEvent']['Track'] = '';
    $form_state['values']['TracksSessions']['SuperEvent']['Track']['Title'] = $track_val[1];
    $form_state['values']['TracksSessions']['SuperEvent']['Track']['Acronym'] = $track_val[0];
  }
  
  // Handle file uploads
  $validators = array();
 
  // File upload
  $fileObject = NULL;
  //Check if it's already there; this is what upload_element provides.
  if (is_a($form_state['values']['RepositoryFile']['ingest-file-location'], 'stdClass') && property_exists($form_state['values']['RepositoryFile']['ingest-file-location'], '')) {
    $fileObject = $form_state['values']['RepositoryFile']['ingest-file-location'];
  }
  elseif (!empty($_FILES['files']['name']['RepositoryFile'])) {
    $fileObject = file_save_upload('RepositoryFile', $validators);
  }

  if ($fileObject !== NULL && property_exists($fileObject, 'filepath')) {
    file_move($fileObject->filepath, 0, 'FILE_EXISTS_RENAME');
    $form_state['values']['ingest-file-location'] = $fileObject->filepath;
  }

  // Logo
  $fileObject = NULL;
  //Check if it's already there; this is what upload_element provides.
  if (is_a($form_state['values']['RepositoryTechnicalities']['Logo'], 'stdClass') && property_exists($form_state['values']['RepositoryTechnicalities']['Logo'], '')) {
    $fileObject = $form_state['values']['RepositoryTechnicalities']['Logo'];
  }
  elseif (!empty($_FILES['files']['name']['RepositoryTechnicalities'])) {
    $fileObject = file_save_upload('RepositoryTechnicalities', $validators);
  }

  if ($fileObject !== NULL && property_exists($fileObject, 'filepath')) {
    file_move($fileObject->filepath, 0, 'FILE_EXISTS_RENAME');

    $image = imageapi_image_open($fileObject->filepath);
    $return_value = imageapi_image_scale($image, 100, 100);
    $return_value = imageapi_image_close($image);
    if ($return_value) {
      $_SESSION['fedora_ingest_files']["TN"] = $fileObject->filepath;
    }
  }

  if (!empty($form_state['values']['RepositoryFile']['PullURL'])) {
    if (in_array(parse_url($form_state['values']['RepositoryFile']['PullURL'], PHP_URL_SCHEME), array('http', 'https'))) {
      $data = file_get_contents($form_state['values']['RepositoryFile']['PullURL']);

      $file = file_directory_path() . '/' . time() . '-tmp';
      file_put_contents($file, $data);
      $_SESSION['fedora_ingest_files']["OBJ"] = $file;
    }
  }
}

function dtu_conf_submit($form, &$form_state) {
  if (!empty($form_state['values']['RepositoryTechnicalities']['ConferenceBaseURL'])) {
    dtu_multisite_update($form_state['values']['pid'], $form_state['values']['RepositoryTechnicalities']['ConferenceBaseURL']);
  }
}

function dtu_islandora_object_clone_prepare_xml_alter($xml_string, $ds_id) {
  $ds_id = strtolower($ds_id);

  switch ($ds_id) {
    case 'mxe':
      $mxe_xml = new SimpleXMLElement($xml_string);
      unset($mxe_xml->documents);
      $xml_string = $mxe_xml->asXML();
      break;
    case 'ddf':
      $ddf_xml = new SimpleXMLElement($xml_string);
      unset($ddf_xml->publication);
      $xml_string = $ddf_xml->asXML();
      break;
  }
}

function dtu_get_conferences() {
  module_load_include('inc', 'fedora_repository', 'api/fedora_utils');
  $query_string = "select \$object \$title from <#ri>
    where \$object <dc:title> \$title
    and \$object <fedora-model:state> <info:fedora/fedora-system:def/model#Active>
    and \$object <fedora-model:hasModel> <info:fedora/" . CONFERENCE_CMODEL . ">
    order by \$object";

  $object_info = dtu_object_pid_query($query_string);
  
  return $object_info;
}

function dtu_get_contributions($pid) {
  module_load_include('inc', 'fedora_repository', 'api/fedora_utils');
  $query_string = "select \$object \$title from <#ri>
    where \$object <dc:title> \$title
    and \$object <fedora-model:state> <info:fedora/fedora-system:def/model#Active>
    and \$object <info:fedora/fedora-system:def/relations-external#isMemberOfCollection> <info:fedora/$pid>
    and \$object <fedora-model:hasModel> <info:fedora/" . CONTRIBUTION_CMODEL . ">
    order by \$object";

  $object_info = dtu_object_pid_query($query_string);
  
  return $object_info;
}

function dtu_get_contrib_tracks_sess($pid, $type = 'tra', $form) {
  module_load_include('inc', 'fedora_repository', 'api/fedora_item');
  module_load_include('inc', 'fedora_repository', 'api/fedora_utils');

  // Consequence of this brittle setup, AHAH requests have different args()
  if (!valid_pid($pid)) {
    $pid = $_POST['pid'];
  }

  $tracks = array();

  $conf_pid = $_GET['conf'];

  if (is_null($conf_pid) && valid_pid($pid)) {
    $cont = new Fedora_Item($pid);
    $rels_ext = $cont->get_rdf_relationships();
    $conf_pid = $rels_ext['fedora:isMemberOfCollection'][1];
  }


  if (valid_pid($conf_pid)) {
    $conf = new Fedora_Item($conf_pid);
  }
  else {
    //$conf = new Fedora_Item();
  }

  if ($conf) {
    $mxe = $conf->get_datastream_dissemination('MXE');
    $mxe_xml = simplexml_load_string($mxe);

    if ($mxe_xml) {
      $mxe_xml->registerXPathNamespace('mxe', 'http://mx.dtic.dk/ns/mxe_draft');
      $tracks_query = $mxe_xml->xpath('//mxe:sub_events/mxe:sub_event[@event_type="' . $type .'"]');
      foreach ($tracks_query AS $track) {
        $title = (string) $track->children('http://mx.dtic.dk/ns/mxe_draft')->title;
        $key = (string) $track->children('http://mx.dtic.dk/ns/mxe_draft')->acronym . '--delim--' . $title;
        $tracks[$key] = $title;

      }
    }
  }

  if (empty($tracks)) {
    switch ($type) {
      case 'tra':
        $tracks = $form['TracksSessions']['SuperEvent']['Track']['Title']['#options'];
        break;
      case 'ses': {
        $tracks = $form['TracksSessions']['SuperEvent']['Session']['Title']['#options'];
        break;
      }
    }
  }
  return $tracks;
}

/**
 * 
 * @param string $pid
 * @param boolean $delete_tree
 *   TRUE if all child objects should also be deleted
 * @param boolean $delete_conf
 *   TRUE if the conference should be deleted
 */
function dtu_delete_conference($pid, $delete_tree = TRUE, $delete_conf = TRUE) {
  module_load_include('inc', 'fedora_repository', 'api/fedora_item');

  // Delete sub-collections: Documents, Contribution

  $query_string = "select \$object \$title from <#ri>
    where \$object <dc:title> \$title
    and \$object <fedora-model:state> <info:fedora/fedora-system:def/model#Active>
    and \$object <info:fedora/fedora-system:def/relations-external#isMemberOfCollection> <info:fedora/$pid>
    and \$object <fedora-model:hasModel> <info:fedora/islandora:collectionCModel>
    order by \$object";

  $sub_collections = dtu_object_pid_query($query_string);

  foreach ($sub_collections AS $sub_col) {
    $item = new Fedora_Item($sub_col['pid']);
    $item->purge('Purged via dtu module');
    drupal_set_message('Item purged: ' . $item->objectProfile->objLabel);
  }

  // Delete child documents
  $documents = dtu_get_contribution_documents($pid);
  foreach ($documents AS $document) {
    dtu_delete_document($document['pid']);
  }

  if ($delete_tree) {
    $contributions = dtu_get_contributions($pid);
    foreach ($contributions AS $contribution) {
      dtu_delete_contribution($contribution['pid']);
    }
  }
  
  // Delete conference
  if ($delete_conf) {
    $item = new Fedora_Item($pid);
    $item->purge('Purged via dtu module');
    drupal_set_message('Item purged: ' . $item->objectProfile->objLabel);
  }
}

function dtu_delete_contribution($pid) {
  // Delete contribution
  $item = new Fedora_Item($pid);
  $item->purge('Purged via dtu module');
  drupal_set_message('Item purged: ' . $item->objectProfile->objLabel);
}

function dtu_delete_document($pid) {
  module_load_include('inc', 'fedora_repository', 'api/fedora_item');
  
  // Delete document
  $item = new Fedora_Item($pid);
  $item->purge('Purged via dtu module');
  drupal_set_message('Item purged: ' . $item->objectProfile->objLabel);
}

function dtu_get_contribution_documents($pid) {
  module_load_include('inc', 'fedora_repository', 'api/fedora_utils');
  $query_string = "select \$object \$title from <#ri>
    where \$object <dc:title> \$title
    and \$object <fedora-model:state> <info:fedora/fedora-system:def/model#Active>
    and \$object <info:fedora/fedora-system:def/relations-external#isMemberOfCollection> <info:fedora/$pid>
    and \$object <fedora-model:hasModel> <info:fedora/" . DOCUMENT_CMODEL . ">
    order by \$object";
  $object_info = dtu_object_pid_query($query_string);

  return $object_info;
}

function dtu_object_pid_query($query_string) {
  $query_string = urlencode($query_string);

  $url = variable_get('fedora_repository_url', 'http://localhost:8080/fedora/risearch');
  $url .= "?type=tuples&flush=TRUE&format=Sparql&lang=itql&stream=on&query=". $query_string;
  $content = do_curl($url);

  $results = simplexml_load_string($content);

  $object_info = array();
  foreach ($results->results->result AS $result) {
    $pid = (string) $result->object['uri'][0];
    $pid = preg_replace('/^info:fedora\//', '', $pid);
    $object_info[] = array('pid' => $pid, 'title' => (string) $result->title);
  }

  return $object_info;
}

function dtu_islandora_object_event($function, $parameters, $result) {
  module_load_include('inc', 'fedora_repository', 'api/fedora_item');
  
  switch($function) {
    
    case 'ingest':
      if (isset($result->objectPID)) {
        $object = new Fedora_Item($result->objectPID);
        $rels = $object->get_rdf_relationships();
        
        if (!empty($rels)) {
          // Conference has been ingested
          if (in_array(CONFERENCE_CMODEL, $rels['fedora-model:hasModel'])) {
            module_load_include('inc', 'dtu', 'inc/Conference');
            $conference = new Conference($object);
            $conference->create();
          }
          
          // Contribution has been ingested
          if (in_array(CONTRIBUTION_CMODEL, $rels['fedora-model:hasModel'])) {
            module_load_include('inc', 'dtu', 'inc/Contribution');
            $contribution = new Contribution($object);
            $contribution->create();
          }
          
          // Document has been ingested
          if (in_array(DOCUMENT_CMODEL, $rels['fedora-model:hasModel'])) {
            module_load_include('inc', 'dtu', 'inc/Document');
            $document = new Document($object);
            $document->create();
          }
        }
      }
      break;
      
    case 'modifyDatastreamByValue':
      if (isset($parameters['pid'])) {
        $object = new Fedora_Item($parameters['pid']);
        $rels = $object->get_rdf_relationships();
        
        if (!empty($rels)) {
          // Conference MXE updated
          if (in_array(CONFERENCE_CMODEL, $rels['fedora-model:hasModel']) && $parameters['dsID'] == 'MXE') {
            module_load_include('inc', 'dtu', 'inc/Conference');
            $conference = new Conference($object);
            $conference->update();
          }

          // Contribution MXE updated
          if (in_array(CONTRIBUTION_CMODEL, $rels['fedora-model:hasModel']) && $parameters['dsID'] == 'MXE') {
            module_load_include('inc', 'dtu', 'inc/Contribution');
            $contribution = new Contribution($object);
            $contribution->update();
          }

          // Document DDF updated
          if (in_array(DOCUMENT_CMODEL, $rels['fedora-model:hasModel']) && $parameters['dsID'] == 'DDF') {
            
          }
        }
      }
      break;
  }
}

// Not used
// Map people to orgs via add_no attribute
function dtu_mxe_tidy(&$mxe_xml) {
  $people = $mxe_xml->xpath('//mxe:person');

  $modified = 0;
  $people_count = 1;
  foreach ($people AS $person) {
    $has_aff = FALSE;
    foreach ($person->attributes() AS $att => $val) {
      if ($att == 'aff_no') {
        $has_aff = TRUE;
      }
    }

    if (!$has_aff) {
      $person->addAttribute('aff_no', $people_count);
      $modified++;
    }

    $people_count++;
  }

  $orgs = $mxe_xml->xpath('/mxe:eve/mxe:organisation');
  $org_count = 1;
  foreach ($orgs AS $org) {
    $has_aff = FALSE;
    foreach ($org->attributes() AS $att => $val) {
      if ($att == 'aff_no') {
        $has_aff = TRUE;
      }
    }

    if (!$has_aff) {
      $org->addAttribute('aff_no', $org_count);
      $org->addAttribute('org_role', 'oaf');
      $modified++;
    }
    $org_count++;
  }

  return $modified;
}


function dtu_multisite_update($pid, $base_url) {
  $multisite_exists = db_result(db_query("SELECT base_url FROM {dtu_multisite} WHERE pid = '%s'", $pid));
  
  $record = array('pid' => $pid, 'base_url' => $base_url);

  // Multisite exists, determine if it should be updated
  if ($multisite_exists) {
    // Multisite needs to be updated
    if ($multisite_exists != $base_url) {
      drupal_write_record('dtu_multisite', $record, 'pid');        
    }
  }
  // Multisite does not exist, create it
  else {    
    drupal_write_record('dtu_multisite', $record);
  }
}

function dtu_get_conference_url($conf_id) {
  $conf_url = db_result(db_query("SELECT base_url FROM {dtu_multisite} WHERE pid = '%s'", $conf_id));
  return $conf_url;
}
